<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
      <tr>
        <th><a href="#"><h1>Entrées<img src="http://img.over-blog-kiwi.com/0/49/12/49/ob_55db6c_avocats-crabe.jpg" alt="entrée"></h1></a></th>
        <th><a href="#"><h1>Plats<img src="https://vivreparis.fr/wp-content/uploads/2018/01/image-1.jpg" alt="plat"></h1></a></th>
        <th><a href="#"><h1>Dessert<img src="https://static.cuisineaz.com/400x320/i107880-milkshake-aux-fraises-tagada.jpg" alt="dessert"></a></th>
        <th><a href="#"><h1>Boissons<img src="https://www.fourchette-et-bikini.fr/sites/default/files/styles/full_670x350/public/1_eau_citronnee_detox.jpg?itok=H_iZ2rmK" alt="boisson"></h1></a></th>
      </tr>
    </tbody>
</table>
<section id="displayCat">
  <!--?php var_dump($categorie) ?-->
</section>
