cartecommande_index:
    path:     /
    defaults: { _controller: "AppBundle:Cartecommande:index" }
    methods:  GET

cartecommande_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cartecommande:show" }
    methods:  GET

cartecommande_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cartecommande:new" }
    methods:  [GET, POST]

cartecommande_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cartecommande:edit" }
    methods:  [GET, POST]

cartecommande_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cartecommande:delete" }
    methods:  DELETE
