carte_index:
    path:     /
    defaults: { _controller: "AppBundle:Carte:index" }
    methods:  GET

carte_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Carte:show" }
    methods:  GET

carte_new:
    path:     /new
    defaults: { _controller: "AppBundle:Carte:new" }
    methods:  [GET, POST]

carte_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Carte:edit" }
    methods:  [GET, POST]

carte_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Carte:delete" }
    methods:  DELETE
