<?php include "loterieFranck.php";?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Loterie php</title>
    <link rel="stylesheet" href="css/normalize.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="css/slider.css">


    <!-- Fonctions utilitaires -->
</head>
<body>
    <header>
      <h1>Loteries</h1>
    </header>
    <main>
      Résultat du tirage :
        <?= displayTirage()?>
    </main>
</body>
</html>
