<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Maquettes</title>
    <link rel="stylesheet" href="css/master.css">
  </head>
  <body>
    <section id="searchform">
      <form class="" action="index.php" method="post">
        <select class="" name="productLine">
          <?php foreach ($categories as $c) : ?>
            <option value='<?= $c['productLine'] ?>'><?= $c['productLine'] ?></option>
          <?php endforeach ?>
        </select>
        <select class="" name="modelYear">
          <?php foreach ($years as $y) : ?>
            <option value='<?= $y['year'] ?>'><?= $y['year'] ?></option>
          <?php endforeach ?>
        </select>
        <input type="submit" value='Chercher' />
      </form>
    </section>
    <section id="searchResults">
      <?php if (isset($models)) : ?>
      <table>
        <caption class=resultTableCaption align='top'>Critères de recherche : Categorie = <?= $searchCategorie ?> & Année = <?= $searchYear ?></caption>
        <thead>
          <tr>
            <th>Nom du modèle</th>
            <th>Catégorie du modèle</th>
            <th class='description'>Description</th>
            <th>Prix de vente</th>
            <th>Modifier</th>

          </tr>
        </thead>
        <tbody>
          <?php foreach($models as $m) : ?>
            <tr>
              <td><?= $m['productName'] ?></td>
              <td><?= $m['productLine'] ?></td>
              <td><?= $m['productDescription'] ?></td>
              <td><?= $m['MSRP'] ?></td>
              <td>
                <a href="update.php?id=<?= $m['productCode'] ?>">Modifier</a>
              </td>
            </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    <?php endif ?>
    </section>
  </body>
</html>
