<?php

namespace AppBundle\Repository;

/**
 * CartecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartecommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
