category_public_index:
    path:     /
    defaults: { _controller: "AppBundle:Category:index" }
    methods:  GET

category_public_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Category:show" }
    methods:  GET

category_index:
    path:     /admin
    defaults: { _controller: "AppBundle:Category:index" }
    methods:  GET

category_show:
    path:     /admin/{id}/show
    defaults: { _controller: "AppBundle:Category:show" }
    methods:  GET

category_new:
    path:     /admin/new
    defaults: { _controller: "AppBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "AppBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "AppBundle:Category:delete" }
    methods:  DELETE
