user_public_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_public_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET


user_index:
    path:     /admin
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /admin/{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

user_new:
    path:     /admin/new
    defaults: { _controller: "AppBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE
