
<header>
  <div class=" header_content container">
    <div id="logo">
      <a href="index.php"><img src="images/bird1.svg" id="img_logo" alt="bird"/><h1>TUI TUI LAND</h1></a>
    </div>
    <nav>
      <ul>
        <li><a href="index.php"><h2>Accueil</h2></a></li>
        <li><a href="#"><h2>Ile du nord</h2></a></li>
        <li><a href="#"><h2>Ile du sud</h2></a></li>
        <li><a href="#"><h2>bla...</h2></a></li>
        <li><a href="newBillet.php"><h2>Nouveau Billet</h2></a></li>
      </ul>
    </nav>
  </div>
</header>
