<?php session_start();
if (isset ($_SESSION['connect'])) {
  $connect = $_SESSION['connect'];
} else {
  $connect = false;
}
 // creation de la variable $_SESSION pour empêcher l'apparition d'une erreur indiquant qu'elle n'existe pas
?>

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="public/css/normalize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="public/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Signika|Thasadith" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <script type="text/javascript" src="public/js/utilities.js"></script>
    <script type="text/javascript" src="public/js/main.js"></script>
    <title>Tuitui Blog</title>
  </head>
  <body>
    <main class="container bgopaque flex">
      <section id="section_billet" class="clear">
        <?php include "template/home.phtml"; ?>
      </section>
      <div  id="aside" class="col-one-third clear">
         <?php if (!$connect): ?>
          <form class="connexion" action="src/repository/connexion.php" method="post">
            <fieldset>
              <legend>Connexion</legend>
              <ul>
                <li>
                  <input type="text" name="pseudo" placeholder="pseudo" />
                </li>
                <li>
                  <input type="password" name="pw" placeholder="password"  >
                </li>
                <li>
                  <button type="submit" name="button">Valider</button>
                </li>
              </ul>
            </fieldset>
          </form>
          <a href="register.php"><h4>Devenir membre</h4></a>
        <?php else: ?>
          <div id="connected">
            <h3><i class="fas fa-heart"></i> Bonjour <?php  if($_SESSION['pseudo']){
              echo $_SESSION['pseudo'];
            }  ?><i class="fas fa-heart"></i></h3>
            <a href="src/repository/deconnexion.php">Se déconnecter</a>
            <a href="newBillet.php"><h3>Créer un nouveau Billet</h3></a>
          </div>
        <?php endif; ?>
          <div id="search">
            <form action="search.php" method="post">
              <input type="text" name="search" value="">
              <button type="submit" name="button">Rechercher</button>
            </form>
          </div>
          <div id="categ">
            <h3>Catégorie</h3>

            <?php foreach($displayCat_result as $c): ?>
              <p><?= $c['nom']; ?></p>
            <?php endforeach ?>

          </div>
        </div>
    </main>
  </body>

</html>
