<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Signika|Thasadith" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <title>Tuitui Blog</title>
  </head>
  <body>
    <form class="container" action="index.html" method="post">
      <fieldset >
        <legend><h2>Nouveau billet</h2></legend>
        <label for="title">
          <input type="text" name="title" id="title" placeholder="Titre" value="">
        </label>
        <label for="categorie"></label>
        <select class="categorie" name="">
          <option value="">Sélectionner un thème</option>
          <option value="">Ile du sud</option>
        </select>
        <input type="date" name="" value="">
        <textarea name="name" rows="8" cols="80"></textarea>
        <input type="image" id="image" name="image" value="" src="">
        <label for="save"></label>
        <button type="button" name="button" value="send">Enregistrer</button>
      </fieldset>
    </form>
  </body>
</html>
