<h2><?= $message ?></h2>
<form class="connexion" action="user/login" method="post">
  <fieldset>
    <legend>Connexion</legend>
        <label for="pseudo">
        <input type="text" id="pseudo" name="pseudo" placeholder="pseudo" value="">
        </label>
        <label for="pw">
        <input type="password"  id="pw" placeholder="password" name="pw" value="">
        </label>
        <button type="button" name="button">Valider</button>
  </fieldset>
</form>
