<h2><?= $message ?></h2>
<form class="registerForm" action='application/controllers/insertMeal/InsertMealController.php' method="post">
  <fieldset>
      <legend><h2>Description du nouveau plat</h2></legend>
      <input type="text" name="nom_plat"  placeholder="Nom du plat">
      <input type="text" name="cat_plat" placeholder="categorie"/>
      <textarea name="description" rows="8" cols="40" placeholder="Description"></textarea>
    
      <input type="number" name="stock" placeholder="quantité"/>
      <input type="number" name="prix" placeholder="prix"/>
      <button type="submit" name="button" value="">Enregistrer</button>
  </fieldset>
</form>
