
<h2><?= $message ?></h2>
<form class="registerForm" action='application/controllers/user/RegisterController.php' method="post">
  <fieldset>
      <legend><h2>Créez un compte client</h2></legend>
      <input type="text" name="nom"  placeholder="Nom">
      <input type="text" name="prenom" placeholder="Prenom"/>
      <textarea name="adress" rows="8" cols="40" placeholder="Adresse"></textarea>
      <input type="text" name="pseudo" placeholder="Pseudo"/>
      <input type="email" name="email" placeholder="@"/>
      <input type="tel" name="tel" placeholder="tel"/>
      <input type="password" name="pw" placeholder="Mot de passe">
      <button type="submit" name="button" value="">Enregistrer</button>
  </fieldset>
</form>
